name: "CI - libmodule"

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - libs/libmodule/**

defaults:
  run:
    working-directory: libs/libmodule

jobs:
  check:
    name: "Checks and Tests"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: NPM Lint and Tests ${{ matrix.node-version }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run lint
      - run: npm run test
