name: "CI and Release"

on:
  push:
    branches: [main]
  pull_request:

# For auto-approving/merging PRs.
permissions:
  pull-requests: write
  contents: write

jobs:
  check:
    name: "Checks and Tests"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - name: "Run NPM Basic Checks"
        uses: SkynetLabs/.github/.github/actions/npm-basic-checks@master
        with:
          node-version: ${{ matrix.node-version }}

